language: generic

arch: amd64

os: linux

dist: bionic

addons:
  apt:
    packages:
      - jq
      - moreutils
      - wget
      - curl

before_install:
  - sudo apt-get update
  - curl -fsSL test.docker.com -o get-docker.sh && sh get-docker.sh
  - sudo usermod -aG docker $USER
  - mkdir -p ~/.docker
  - test -f ~/.docker/config.json || echo "{}" >  ~/.docker/config.json

before_script:
  - docker version
  - "jq --arg experimental enabled '. + {experimental: $experimental}' ~/.docker/config.json | sponge ~/.docker/config.json" # enable experimental features in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

env:
  - PLATFORM=linux/amd64
  - PLATFORM=linux/arm64
  - PLATFORM=linux/arm/v7

script: travis_wait 30 ./ci/buildx-docker-arch.sh $PLATFORM
