language: generic

os: linux

dist: bionic

addons:
  apt:
    packages:
      - jq
      - moreutils
      - wget
      - curl

before_install:
  - sudo apt-get update
  - curl -fsSL test.docker.com -o get-docker.sh && sh get-docker.sh
  - sudo usermod -aG docker $USER
  - mkdir -p ~/.docker
  - test -f ~/.docker/config.json || echo "{}" >  ~/.docker/config.json

before_script:
  - docker version
  - "jq --arg experimental enabled '. + {experimental: $experimental}' ~/.docker/config.json | sponge ~/.docker/config.json" # enable experimental features in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: build
      arch: amd64
      script: ./ci/build-docker-arch.sh amd64
    - stage: build
      arch: arm64
      script: ./ci/build-docker-arch.sh arm64
    - stage: build
      arch: arm64
      script:
        - wget https://github.com/docker/buildx/releases/download/v0.2.0/buildx-v0.2.0.linux-arm64
        - mkdir -p ~/.docker/cli-plugins/
        - mv buildx-v0.2.0.linux-arm64 ~/.docker/cli-plugins/docker-buildx
        - chmod +x ~/.docker/cli-plugins/docker-buildx
        - ./ci/buildx-docker-arch.sh linux/arm/v7
    - stage: build
      arch: amd64
      script:
        - wget https://github.com/docker/buildx/releases/download/v0.2.0/buildx-v0.2.0.linux-amd64
        - mkdir -p ~/.docker/cli-plugins/
        - mv buildx-v0.2.0.linux-amd64 ~/.docker/cli-plugins/docker-buildx
        - chmod +x ~/.docker/cli-plugins/docker-buildx
        - docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
        - ./ci/buildx-docker-arch.sh linux/arm/v7
    - stage: manifest
      script: ./ci/build-docker-manifest.sh
