language: generic

os: linux

before_script:
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

services:
  - docker

jobs:
  include:
    - stage: build
      arch: amd64
      script: ./ci/build-docker-arch.sh amd64
    - stage: build
      arch: arm64
      script: ./ci/build-docker-arch.sh arm64
    - stage: manifest
      addons:
        apt:
          packages:
            - jq
            - moreutils
      script:
        - "jq --arg experimental enabled '. + {experimental: $experimental}' ~/.docker/config.json | sponge ~/.docker/config.json" # enable experimental features in docker CLI
        - ./ci/build-docker-manifest.sh
