apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-client-a-via-pod-selector-with-match-expressions
  namespace: default
spec:
  podSelector:
    matchLabels:
      pod-name: pod-server
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - key: pod-name
          operator: In
          values:
          - client-a
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    pod-name: pod-server
spec:
  containers:
  - image: busybox
    command: ["tail"]
    args: ["-f", "/dev/null"]
    imagePullPolicy: IfNotPresent
    name: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    pod-name: client-a
spec:
  containers:
  - image: busybox
    command: ["tail"]
    args: ["-f", "/dev/null"]
    imagePullPolicy: IfNotPresent
    name: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox3
  labels:
    pod-name: client-b
spec:
  containers:
  - image: busybox
    command: ["tail"]
    args: ["-f", "/dev/null"]
    imagePullPolicy: IfNotPresent
    name: busybox
