name: buildx

on:
  push:
    branches: experiment-with-travis-arm-builder

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx
        env:
          OVS_VERSION: 2.13.0
          PLATFORMS: "linux/amd64,linux/arm/v7,linux/arm64"
        run: |
          cd build/images/ovs && docker buildx build -t antrea/openvswitch:$OVS_VERSION --platform $PLATFORMS --build-arg OVS_VERSION=$OVS_VERSION . && cd -
          docker buildx build -t antoninbas/antrea-ubuntu-march --platform $PLATFORMS -f build/images/Dockerfile.build.ubuntu .
