name: Scan Antrea Docker image for vulnerabilities every day

on:
  push:
    branches:
      - scan-latest-antrea-docker-image-for-vulnerabilities-test

jobs:
  build:
    if: github.repository != 'vmware-tanzu/antrea'
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Scan Antrea Docker image for vulnerabilities
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SES }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SES }}
      run: |
        cd ci/clair-scan
        ./run.sh
