name: Go Test
on:
  push:
    branches:
    - test-rotate-certificate

jobs:
  test-unit:
    runs-on: [ubuntu-latest]
    steps:
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Set up Go using version from go.mod
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - name: Run unit tests
      run: go test -race -count=30 ./pkg/agent/controller/ipseccertificate/...
